### ISSUE TITLE
[BUG] while構文内のローカル変数が２回目以降のループで宣言済みとしてエラーになる

### ISSUE THREAD

**Issue by avaice** [avaice/icecript#20]
## 確認したバージョン
 `0.3.1a`

## 内容
while構文内のローカル変数が２回目以降のループで宣言済みとしてエラーになる

## エラー時のトレースやスクリーンショット等
```
% npm start ./samples/max_age.ic                                                          

> icecript@0.2.1 start
> ts-node src/main.ts ./samples/max_age.ic

チームの名前を教えてください: おやすみ
おやすみの所属人数を教えてください: 3
1人目の年齢を教えてください: 80
2人目の年齢を教えてください: 99
/Users/user/Repository/icecript/src/tools.ts:32
    throw new Error(`\x1b[31m${message}\n${p}: ${pos}\x1b[0m`)
          ^
Error: 宣言済みの変数 "age" を再宣言することはできません
49: i + "人目の年齢を教えてください" ) var age = parse ( "int"
    at err (/Users/user/Repository/icecript/src/tools.ts:32:11)
    at /Users/user/Repository/icecript/src/interpriter.ts:193:12
    at Generator.next (<anonymous>)
    at /Users/user/Repository/icecript/src/interpriter.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/user/Repository/icecript/src/interpriter.ts:4:12)
    at defineVar (/Users/user/Repository/icecript/src/interpriter.ts:180:53)
    at /Users/user/Repository/icecript/src/interpriter.ts:41:22
    at Generator.next (<anonymous>)
    at /Users/user/Repository/icecript/src/interpriter.ts:8:71
```

**Comment by avaice** [comment]
関数以外はローカル変数を持たない仕様。直した方がいいけど
